export const ADD_TO_SURVEYQUESTION = "ADD_TO_SURVEYQUESTION";
export const ADD_TO_SURVEYANSWERS = "ADD_TO_SURVEYANSWERS";
export const UPDATE_TO_SURVEYQUESTION = "UPDATE_TO_SURVEYQUESTION";
export const DEL_AND_QA = "DEL_AND_QA";